name: yi-config
version: 0.1.0.0
license: BSD3
maintainer: aiya000.develop@gmail.com
github: aiya000/dotfiles
category: Yi

dependencies:
    - base >= 4.8 && < 5
    - cmdargs
    - containers
    - extra
    - microlens
    - microlens-platform
    - mtl
    - oo-prototypes
    - pointedlist
    - yi-core
    - yi-keymap-emacs
    - yi-keymap-vim
    - yi-language
    - yi-misc-modes
    - yi-mode-haskell
    - yi-rope
    - transformers-base
    - unordered-containers
    - text
    - easy-file

executables:
    yi:
        main: Main.hs
        source-dirs: .
        other-modules:
            Yi.MyConfig.CmdOptions
          , Yi.MyConfig.Helper
