flags: {}
packages:
- .
- location: ./yi-origin
  subdirs:
  - yi-core
  - yi-frontend-vty
  - yi-frontend-pango
  - yi-keymap-vim
  - yi-keymap-emacs
  - yi-misc-modes
  - yi-mode-haskell
  - yi-mode-javascript
- location: .
  subdirs:
  - yi-rope
extra-deps:
- gio-0.13.4.1
- gtk-0.14.7
- yi-language-0.17.1
resolver: lts-11.3
